# 차트 데이터 

In [7]:
from dbQuery import dbQuery, dfFilter, dfPlot

# 속성 추출
1. 차트 진입후 5위 이내까지 진입한 일수
2. 해당 곡 아티스트의 다른 곡이 차트에 진입한 일수
3. 차트 진입 후 5위 이내까지 일간 랭킹 상승 평균치
4. 네이버 트렌드와 음원차트의 상관계수
5. and more...

In [4]:
# 데이터베이스 내 음원의 수 = 학습시킬 레코드의 수

# 쿼리문 입력
query = """ SELECT DISTINCT title  FROM zuzak.genie; """

Chartdf = dbQuery(query)

# 쿼리결과 없으면
if Chartdf.empty:
    print('결과 데이터가 없습니다.')

# 쿼리 결과
else :
    print(Chartdf)
    all_song = Chartdf
    print('총 음원의 수 = '+str(len(Chartdf)))
    #데이터 정보 출력
    print(Chartdf.describe())


                                                 title
0                                         또하루(Feat.개코)
1                                                   소녀
2                                              걱정말아요그대
3                                                 어땠을까
4                                                   함께
5                                 DADDY(Feat.CLof2NE1)
6                                           혜화동(혹은쌍문동)
7                                            OOH-AHH하게
8                                                 나팔바지
9                                  19금유레카(Feat.Zion.T)
10                                        청춘(Feat.김창완)
11                                               우주를건너
12                                               또다시사랑
13                    BoysAndGirls(Feat.Babylon(베이빌론))
14                                               매일그대와
15                                        네게줄수있는건오직사랑뿐
16                                화이트(WHITE)(Feat.박재범)
17        

In [26]:
all_song.head()

title
0  또하루(Feat.개코)
1            소녀
2       걱정말아요그대
3          어땠을까
4            함께

In [38]:
for i, songtitle in enumerate(all_song['title']):
    # 딥러닝 학습 코드 
    

0 또하루(Feat.개코)
1 소녀
2 걱정말아요그대
3 어땠을까
4 함께
5 DADDY(Feat.CLof2NE1)
6 혜화동(혹은쌍문동)
7 OOH-AHH하게
8 나팔바지
9 19금유레카(Feat.Zion.T)
10 청춘(Feat.김창완)
11 우주를건너
12 또다시사랑
13 BoysAndGirls(Feat.Babylon(베이빌론))
14 매일그대와
15 네게줄수있는건오직사랑뿐
16 화이트(WHITE)(Feat.박재범)
17 오늘부터우리는(Megustastu)
18 I(Feat.버벌진트)
19 HOTPINK
20 스물셋
21 못먹는감(SourGrapes)
22 SingForYou
23 Hello
24 사랑이맞을거야
25 취향저격
26 NoMakeUp
27 사랑,어른이되는것
28 아니라고
29 이럴거면그러지말지(Feat.YoungK)
30 Ah-Choo
31 세월이가면
32 불공평해(Unfair)
33 꺼내먹어요
34 DearSanta
35 위잉위잉
36 겁(Feat.태양)
37 야생화
38 심쿵해(HeartAttack)
39 바람이나좀쐐(Feat.우혜미)
40 다시(Feat.유재석)
41 덤앤더머(DUMB&DUMBER)
42 양화대교
43 DumbDumb
44 어깨
45 널생각해(Prod.by이찬혁of악동뮤지션)
46 같은시간속의너
47 보통연애(Feat.박보람)
48 Dream(Feat.XIAofJYJ)
49 모르나봐
50 밤의멜로디
51 뱅뱅뱅(BANGBANGBANG)
52 음오아예(UmOhAhYeh)
53 MustHaveLove(Feat.에릭남)
54 Sugar
55 4Walls
56 I'mNotTheOnlyOne
57 친구라도될걸그랬어
58 푸르던
59 레옹
60 IRememberYou(Feat.Zion.T)
61 웃픈하루
62 리듬타(RHYTHMTA)
63 LionHeart
64 RUN
65 지못미
66 LostStars
67 북두칠성
68 오빠차
69 왜또
70 오만과편견(Feat.수란)
71 But(Feat.백지영)
72 Zeze
73 허세(Pr

1270 네게
1271 KNOCKKNOCK
1272 좋아해(Bye)
1273 녹아요
1274 내가너가
1275 행복을주는사람
1276 남녀의온도차(OurStory)(Feat.케이시)
1277 니가보고싶은밤
1278 눈물(Tears)
1279 너만생각나
1280 LetMeLoveYou
1281 많이사랑했나보다
1282 언젠가(SOMEDAY)
1283 Wi-Fi
1284 너만없다
1285 내일그대와
1286 LoveYourself
1287 그대란정원
1288 WoW!
1289 나같은애(AGirlLikeMe)
1290 낡은그리움
1291 Fine
1292 날개(FeelSoFine)
1293 CoverUp
1294 IGotLove
1295 TimeLapse
1296 WhenIWasYoung
1297 수채화(LoveinColor)
1298 I'mOK
1299 LonelyNight
1300 SweetLove
1301 기다리지말아요
1302 Fire
1303 Eraser
1304 ShapeOfYou
1305 눈을보고말해요
1306 19금마에스트로(Maestro)
1307 FINGERTIP
1308 MOVIE
1309 바람의노래(HearTheWindSing)
1310 ABOUTTIME
1311 말만해
1312 봄비(RainInTheSpringTime)
1313 빨리뛰어(ROCKNHIPHOP)
1314 나의지구를지켜줘(PleaseSaveMyEarth)
1315 비행운:飛行雲(Contrail)
1316 어떻게말해
1317 핑(Crush)
1318 부담이돼(Feat.휘인of마마무)
1319 HulkHogan(헐크호건)
1320 그래사랑이었다.
1321 유후(You,Who?)
1322 나야나(PICKME)
1323 어떨까
1324 아름답다
1325 NeverEver
1326 바램
1327 하루만큼하루만더
1328 북극곰
1329 우리(Feat.YunB)
1330 집이있었지
1331 그랬을까
1332 별처럼
1333 나무
1334 PIZZA
1335 사랑은지옥에서온개(Feat.수란)

2519 ByeBabe
2520 만약에(If)
2521 11°
2522 오늘따라예쁘다
2523 우리라는세상
2524 BlackSuit
2525 박수
2526 혼자야
2527 ShallWeDance
2528 아주멀지않은날에
2529 일방적이야
2530 되돌리고싶다(Rewind)
2531 듣고싶은말
2532 운명
2533 Twilight
2534 NothingWithoutYou(Intro.)
2535 퇴근(Feat.박재범&Crush)
2536 활활(BurnItUp)(PrequelRemix)
2537 에너제틱(Energetic)(PrequelRemix)
2538 ToBeOne(Outro.)
2539 종소리
2540 너의계절
2541 말이되니
2542 하나만해(Can'tWait)
2543 NoSwitchin'Sides
2544 봐(Look)
2545 IJust
2546 KingdomCome
2547 두번째데이트(MySecondDate)
2548 달빛소리(MoonlightMelody)
2549 AboutLove
2550 Attaboy
2551 Perfect10
2552 끝이아닌것같아서
2553 이별선물
2554 갈수가없어
2555 동성로(Feat.Crush)
2556 눈꽃,그거리에서(Feat.오은하)
2557 더(Prod.by브라더수)
2558 OK(Prod.byGRAY)
2559 오늘헤어져(Feat.조현아of어반자카파)
2560 MICDrop(SteveAokiRemix)(Feat.Desiigner)
2561 보는눈(Feat.하니(EXID))
2562 고스란히
2563 SMILE
2564 기억의빈자리(PianoVer.)
2565 문(Prod.byZICO)
2566 바람(Wish)
2567 성냥팔이소녀(TheLittleMatchGirl)
2568 PerfectDuet(WithBeyonce)
2569 안될사랑
2570 첫사랑(Feat.유주of여자친구)
2571 OnlyYou(Feat.유성은)
2572 좋아합니다
2573 사랑하기때문에
2574 크리스마스데이(Christma

In [48]:
# 다른 노래 차트진입일
def chartInDays(title, artist, dbname):
    # 쿼리문 입력
    query = " SELECT * FROM zuzak."+dbname+" where title != '"+title+"' and artist = '"+artist+"' and YYMMDD<= (select YYMMDD from zuzak."+dbname+" where title = '"+title+"' order by YYMMDD limit 1); "
    
    Chartdf = dbQuery(query)
    Chartdf = dfFilter(Chartdf)
    
    
    # 쿼리결과 없으면
    if Chartdf.empty:
        print('결과 데이터가 없습니다.')
        return 0
        
    # 쿼리 결과
    else :        
        return len(Chartdf)

In [54]:
# 다른 노래 차트진입일
chartInDays('좋니', '윤종신','mnet')

11

In [154]:
# 랭킹 상승 평균치
def rankIncreaseMean(title, dbname):
    # 쿼리문 입력
    query = """ SELECT * FROM zuzak."""+dbname+""" where title = '"""+title+"""' and YYMMDD<=
    (select YYMMDD from zuzak."""+dbname+""" where title = '"""+title+"""' and cast(ranking as unsigned) <=5 order by YYMMDD limit 1); """
    
    Chartdf = dbQuery(query)
    Chartdf = dfFilter(Chartdf)
    
    # 쿼리결과 없으면
    if Chartdf.empty:
        print('결과 데이터가 없습니다.')
        return 0
        
    # 쿼리 결과
    elif len(Chartdf) == 1 :
        sum = 100-Chartdf['ranking'][0]
        return sum
    
    else:
        sum = 0
        a = len(Chartdf)
        
        for i in range(1, a):
            num = (Chartdf['ranking'][i-1]) - (Chartdf['ranking'][i])
            sum = sum + num
        
        return sum/(a-1)
    

In [155]:
# 랭킹 상승 평균치
rankIncreaseMean('WayBackHome','genie')

13.166666666666666

In [156]:
# 5위 진입 전까지 일수
def rankInDays(title, dbname):
    # 쿼리문 입력
    query = """ SELECT * FROM zuzak."""+dbname+""" where title = '"""+title+"""' and YYMMDD<=(SELECT YYMMDD FROM zuzak."""+dbname+""" where title = '"""+title+"""' and cast(ranking as unsigned) <=5  order by YYMMDD limit 1); """
    Chartdf = dbQuery(query)
    Chartdf = dfFilter(Chartdf)
    
    # 쿼리결과 없으면
    if Chartdf.empty:
        print('결과 데이터가 없습니다.')
        return 0
        
    # 쿼리 결과
    else :
        return len(Chartdf)

In [157]:
rankInDays('좋니', 'bugs')

48

# 신경망 코드

In [55]:
import tensorflow as tf
import numpy as np

## 18. 8. 1 지니차트 기준 top 15 음원 대상 모델

In [158]:
df = dbQuery('SELECT * FROM zuzak.genie where YYMMDD=180801 and ranking <=15')
df

YYMMDD ranking                           title           artist
0   180801       1              SoulMate(Feat.아이유)         지코(Zico)
1   180801       2                     WayBackHome         숀(SHAUN)
2   180801       3              뚜두뚜두(DDU-DUDDU-DU)        BLACKPINK
3   180801       4               DanceTheNightAway      TWICE(트와이스)
4   180801       5                  너나해(Egotistic)     마마무(Mamamoo)
5   180801       6                            1도없어      Apink(에이핑크)
6   180801       7                              여행           볼빨간사춘기
7   180801       8                           LoveU               청하
8   180801       9                    ForeverYoung        BLACKPINK
9   180801      10  모든날,모든순간(Everyday,EveryMoment)               폴킴
10  180801      11                              동화  멜로망스(MeloMance)
11  180801      12                    셋셀테니(1,2,3!)               승리
12  180801      13              여름여름해(SunnySummer)    여자친구(GFRIEND)
13  180801      14                          너없인안된다              비투비
14  180801      15                            지나오다         닐로(Nilo)

In [163]:
# 주작 = 1
# 여기선 지나오다, way back home 주작으로 가정
labels = np.array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0 ,0, 0, 1])
labels

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1])

In [164]:
# 이전에 차트에 든 일수
chartindays = np.fromiter(map(chartInDays, df['title'], df['artist'], ['genie']*len(df)), np.int32)
chartindays

결과 데이터가 없습니다.
결과 데이터가 없습니다.


array([1578,    0, 1371, 2116, 1309,  216, 3699,  411, 1371,   93,  809,
          1, 1418,  522,    0])

In [165]:
# 랭킹 상승 평균값
rankimean = np.fromiter(map(rankIncreaseMean, df['title'], ['genie']*len(df)), np.int32)
rankimean

결과 데이터가 없습니다.
결과 데이터가 없습니다.


array([99, 13, 99, 98,  1,  1, 99, 98, 97,  1, 98,  0,  0, 96,  6])

In [166]:
# top5 진입 일수
rankindays = np.fromiter(map(rankInDays, df['title'], ['genie']*len(df)), np.int32)
rankindays

결과 데이터가 없습니다.
결과 데이터가 없습니다.


array([ 1,  7,  1,  1,  2,  6,  1,  1,  1, 95,  1,  0,  0,  1, 14])

In [52]:
# [털, 날개]
x_data = np.array(
    [[0, 0], [1, 0], [1, 1], [0, 0], [0, 0], [0, 1]])

# [기타, 포유류, 조류]
# 다음과 같은 형식을 one-hot 형식의 데이터라고 합니다.
y_data = np.array([
    [1, 0, 0],  # 기타
    [0, 1, 0],  # 포유류
    [0, 0, 1],  # 조류
    [1, 0, 0],
    [1, 0, 0],
    [0, 0, 1]
])

#########
# 신경망 모델 구성
######
X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# 신경망은 2차원으로 [입력층(특성), 출력층(레이블)] -> [2, 3] 으로 정합니다.
W = tf.Variable(tf.random_uniform([2, 3], -1., 1.))

# 편향을 각각 각 레이어의 아웃풋 갯수로 설정합니다.
# 편향은 아웃풋의 갯수, 즉 최종 결과값의 분류 갯수인 3으로 설정합니다.
b = tf.Variable(tf.zeros([3]))

# 신경망에 가중치 W과 편향 b을 적용합니다
L = tf.add(tf.matmul(X, W), b)
# 가중치와 편향을 이용해 계산한 결과 값에
# 텐서플로우에서 기본적으로 제공하는 활성화 함수인 ReLU 함수를 적용합니다.
L = tf.nn.relu(L)

# 마지막으로 softmax 함수를 이용하여 출력값을 사용하기 쉽게 만듭니다
# softmax 함수는 다음처럼 결과값을 전체합이 1인 확률로 만들어주는 함수입니다.
# 예) [8.04, 2.76, -6.52] -> [0.53 0.24 0.23]
model = tf.nn.softmax(L)

# 신경망을 최적화하기 위한 비용 함수를 작성합니다.
# 각 개별 결과에 대한 합을 구한 뒤 평균을 내는 방식을 사용합니다.
# 전체 합이 아닌, 개별 결과를 구한 뒤 평균을 내는 방식을 사용하기 위해 axis 옵션을 사용합니다.
# axis 옵션이 없으면 -1.09 처럼 총합인 스칼라값으로 출력됩니다.
#        Y         model         Y * tf.log(model)   reduce_sum(axis=1)
# 예) [[1 0 0]  [[0.1 0.7 0.2]  -> [[-1.0  0    0]  -> [-1.0, -0.09]
#     [0 1 0]]  [0.2 0.8 0.0]]     [ 0   -0.09 0]]
# 즉, 이것은 예측값과 실제값 사이의 확률 분포의 차이를 비용으로 계산한 것이며,
# 이것을 Cross-Entropy 라고 합니다.
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(model), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train_op = optimizer.minimize(cost)


#########
# 신경망 모델 학습
######
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

for step in range(100):
    sess.run(train_op, feed_dict={X: x_data, Y: y_data})

    if (step + 1) % 10 == 0:
        print(step + 1, sess.run(cost, feed_dict={X: x_data, Y: y_data}))


#########
# 결과 확인
# 0: 기타 1: 포유류, 2: 조류
######/''''''''''''''''''''''''''''''''''''''''''''''''''''''
# tf.argmax: 예측값과 실제값의 행렬에서 tf.argmax 를 이용해 가장 큰 값을 가져옵니다.
# 예) [[0 1 0] [1 0 0]] -> [1 0]
#    [[0.2 0.7 0.1] [0.9 0.1 0.]] -> [1 0]
prediction = tf.argmax(model, 1)
target = tf.argmax(Y, 1)
print('예측값:', sess.run(prediction, feed_dict={X: x_data}))
print('실제값:', sess.run(target, feed_dict={Y: y_data}))

is_correct = tf.equal(prediction, target)
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))
print('정확도: %.2f' % sess.run(accuracy * 100, feed_dict={X: x_data, Y: y_data}))

10 1.158742
20 1.154126
30 1.1496745
40 1.1453809
50 1.1412381
60 1.1372404
70 1.1340641
80 1.1328923
90 1.1317396
100 1.130606
예측값: [0 0 0 0 0 1]
실제값: [0 1 2 0 0 2]
정확도: 50.00
